#!/bin/bash
# Vivado下载和安装指南

echo "=========================================="
echo "Vivado下载和安装指南"
echo "=========================================="
echo ""

echo "步骤1：从Xilinx下载Vivado"
echo "-------------------------------"
echo "1. 访问 Xilinx 下载中心："
echo "   https://www.xilinx.com/support/download.html"
echo ""
echo "2. 注册Xilinx账号（如果还没有）"
echo ""
echo "3. 下载 'Vivado ML Edition' 或 'Vivado HLx Edition'"
echo "   推荐：Vivado 2022.1 或更新版本"
echo "   文件名类似：Xilinx_Unified_2022.1_0610_1234_Lin64.bin"
echo "   大小：约25-30GB"
echo ""
echo "4. 选择下载 'Linux Self Extracting Web Installer'"
echo "   或 'Full Product Installation'（完整安装包）"
echo ""

echo "步骤2：设置环境变量"
echo "-------------------------------"
echo "export XILINX_LICENSE_FILE=/home/app/vivado_lic2037.lic"
echo "export PATH=\$PATH:/tools/Xilinx/Vivado/202x.x/bin"
echo ""

echo "步骤3：运行安装程序"
echo "-------------------------------"
echo "cd /home/app/vivado/.xinstall"
echo "bash xsetup"
echo ""

echo "或者，如果下载了完整的.bin文件："
echo "chmod +x Xilinx_Unified_202x.x_xxxxxx_Lin64.bin"
echo "./Xilinx_Unified_202x.x_xxxxxx_Lin64.bin"
echo ""

echo "步骤4：配置许可证"
echo "-------------------------------"
echo "在Vivado安装过程中，或安装后配置："
echo "许可证文件：/home/app/vivado_lic2037.lic"
echo ""

echo "=========================================="
echo "注意事项"
echo "=========================================="
echo "- 需要~30GB磁盘空间"
echo "- 需要~4GB RAM"
echo "- 安装时间：30-60分钟"
echo "- 需要root或sudo权限"
echo ""

echo "=========================================="
echo "快速安装命令（假设已下载.bin文件）"
echo "=========================================="
echo "# 1. 下载Vivado后"
echo "chmod +x Xilinx_Unified_*.bin"
echo ""
echo "# 2. 运行安装"
echo "./Xilinx_Unified_*.bin"
echo ""
echo "# 3. 按提示安装"
echo "  - 选择安装版本：Vivado HL System Edition"
echo "  - 选择安装路径：/tools/Xilinx 或 /home/app/Xilinx"
echo "  - 配置许可证：/home/app/vivado_lic2037.lic"
echo ""
echo "# 4. 设置环境"
echo "source /tools/Xilinx/Vivado/202x.x/settings64.sh"
echo ""
echo "# 5. 验证安装"
echo "vivado -version"
echo "=========================================="
