ARCH_NAME := OS
ARCH_KEY := os
TB_MAIN := $(abspath $(CURDIR)/../tb/systolic_array_os_tb.v)
TB_TOP := systolic_array_os_tb
TB_WAVE := $(abspath $(CURDIR)/../tb/systolic_array_os_latency_tb.v)
TB_WAVE_TOP := systolic_array_os_latency_tb
include $(abspath $(CURDIR)/../../scripts/arch_common.mk)
