#!/usr/bin/env python3
"""
Golden Model for Systolic Array Verification
功能：实现标准的矩阵乘法，作为参考模型验证硬件设计的正确性
"""

import numpy as np
import sys

def matrix_multiply_golden(A, B):
    """
    标准矩阵乘法：C = A × B

    Args:
        A: 输入矩阵 (4x4)
        B: 权重矩阵 (4x4)

    Returns:
        C: 结果矩阵 (4x4)
    """
    return np.dot(A, B)

def test_case_1():
    """测试用例1：所有权重为1，输入为1"""
    print("=" * 60)
    print("测试用例 1: 单位矩阵测试")
    print("=" * 60)

    # 4x4 矩阵，所有元素为1
    A = np.ones((4, 4), dtype=np.int32)
    B = np.ones((4, 4), dtype=np.int32)

    C = matrix_multiply_golden(A, B)

    print("输入矩阵 A (4x4):")
    print(A)
    print("\n权重矩阵 B (4x4):")
    print(B)
    print("\n预期输出 C = A × B:")
    print(C)
    print("\n分析:")
    print("  每个元素 = 1×1 + 1×1 + 1×1 + 1×1 = 4")
    print(f"  预期结果: 所有元素应为 4")
    print(f"  实际结果: {C[0, 0]}, {C[0, 1]}, {C[0, 2]}, {C[0, 3]}")

    # 验证
    expected = 4
    if np.all(C == expected):
        print(f"✅ 测试通过: 所有元素 = {expected}")
    else:
        print(f"❌ 测试失败")

    return A, B, C

def test_case_2():
    """测试用例2：权重为2，输入为3"""
    print("\n" + "=" * 60)
    print("测试用例 2: 常量矩阵测试")
    print("=" * 60)

    # 权重为2，输入为3
    A = np.full((4, 4), 3, dtype=np.int32)
    B = np.full((4, 4), 2, dtype=np.int32)

    C = matrix_multiply_golden(A, B)

    print("输入矩阵 A (4x4):")
    print(A)
    print("\n权重矩阵 B (4x4):")
    print(B)
    print("\n预期输出 C = A × B:")
    print(C)
    print("\n分析:")
    print("  每个元素 = 3×2 + 3×2 + 3×2 + 3×2 = 24")
    print(f"  预期结果: 所有元素应为 24")
    print(f"  实际结果: {C[0, 0]}, {C[0, 1]}, {C[0, 2]}, {C[0, 3]}")

    # 验证
    expected = 24
    if np.all(C == expected):
        print(f"✅ 测试通过: 所有元素 = {expected}")
    else:
        print(f"❌ 测试失败")

    return A, B, C

def test_case_3():
    """测试用例3：随机矩阵"""
    print("\n" + "=" * 60)
    print("测试用例 3: 随机矩阵测试")
    print("=" * 60)

    # 生成小的随机整数矩阵（便于手工验证）
    np.random.seed(42)
    A = np.random.randint(0, 5, (4, 4)).astype(np.int32)
    B = np.random.randint(0, 5, (4, 4)).astype(np.int32)

    C = matrix_multiply_golden(A, B)

    print("输入矩阵 A (4x4):")
    print(A)
    print("\n权重矩阵 B (4x4):")
    print(B)
    print("\n预期输出 C = A × B:")
    print(C)

    # 手工验证第一个元素
    c00 = sum(A[0, :] * B[:, 0])
    print(f"\n手工验证 C[0,0]:")
    print(f"  = {A[0,0]}×{B[0,0]} + {A[0,1]}×{B[1,0]} + {A[0,2]}×{B[2,0]} + {A[0,3]}×{B[3,0]}")
    print(f"  = {A[0,0]*B[0,0]} + {A[0,1]*B[1,0]} + {A[0,2]*B[2,0]} + {A[0,3]*B[3,0]}")
    print(f"  = {c00}")

    if C[0, 0] == c00:
        print(f"✅ 验证通过: C[0,0] = {c00}")
    else:
        print(f"❌ 验证失败")

    return A, B, C

def test_case_4():
    """测试用例4：真实场景模拟（小规模CNN层）"""
    print("\n" + "=" * 60)
    print("测试用例 4: CNN卷积层模拟")
    print("=" * 60)

    # 模拟一个简单的卷积操作
    # 输入特征图 4x4，卷积核 4x4
    input_feature = np.array([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16]
    ], dtype=np.int32)

    kernel = np.array([
        [1, 0, 0, 1],
        [0, 1, 1, 0],
        [1, 1, 0, 0],
        [0, 0, 1, 1]
    ], dtype=np.int32)

    C = matrix_multiply_golden(input_feature, kernel)

    print("输入特征图 (4x4):")
    print(input_feature)
    print("\n卷积核 (4x4):")
    print(kernel)
    print("\n输出特征图 (4x4):")
    print(C)

    print("\n✅ 测试完成")
    return input_feature, kernel, C

def export_test_vectors(A, B, C, test_name):
    """
    导出测试向量，用于 Verilog 仿真

    Args:
        A, B, C: 矩阵
        test_name: 测试名称
    """
    filename = f"test_vectors_{test_name}.txt"

    with open(filename, 'w') as f:
        f.write(f"# Test vectors for {test_name}\n")
        f.write(f"# Generated by golden_model.py\n\n")

        f.write("# 输入矩阵 A (row-major order)\n")
        for i in range(4):
            for j in range(4):
                f.write(f"{A[i,j]} ")
            f.write("\n")

        f.write("\n# 权重矩阵 B (row-major order)\n")
        for i in range(4):
            for j in range(4):
                f.write(f"{B[i,j]} ")
            f.write("\n")

        f.write("\n# 预期输出 C (row-major order)\n")
        for i in range(4):
            for j in range(4):
                f.write(f"{C[i,j]} ")
            f.write("\n")

    print(f"\n📁 测试向量已导出到: {filename}")

def generate_verilog_testbench(A, B, C, test_name):
    """
    生成 Verilog 测试平台，包含自动验证

    Args:
        A, B, C: 矩阵
        test_name: 测试名称
    """
    filename = f"auto_test_{test_name}.v"

    with open(filename, 'w') as f:
        f.write(f"""// Auto-generated testbench for {test_name}
// Generated by golden_model.py

`timescale 1ns/1ps

module auto_test_{test_name};

    parameter DATA_WIDTH = 16;
    parameter WEIGHT_WIDTH = 16;
    parameter ACC_WIDTH = 32;
    parameter CLK_PERIOD = 10;

    reg clk;
    reg rst_n;
    reg [WEIGHT_WIDTH-1:0] weight_in;
    reg weight_valid;
    reg weight_load;
    wire weight_ready;

    reg [DATA_WIDTH-1:0] input_data;
    reg input_valid;
    wire input_ready;

    wire [ACC_WIDTH*4-1:0] output_data;
    wire [3:0] output_valid;
    reg [3:0] output_ready;

    reg flush;
    wire busy;
    reg clk_enable;

    // DUT instantiation
    systolic_array_4x4 #(
        .DATA_WIDTH(DATA_WIDTH),
        .WEIGHT_WIDTH(WEIGHT_WIDTH),
        .ACC_WIDTH(ACC_WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .weight_in(weight_in),
        .weight_valid(weight_valid),
        .weight_load(weight_load),
        .weight_ready(weight_ready),
        .input_data(input_data),
        .input_valid(input_valid),
        .input_ready(input_ready),
        .output_data(output_data),
        .output_valid(output_valid),
        .output_ready(output_ready),
        .flush(flush),
        .clk_enable(clk_enable),
        .busy(busy)
    );

    // Clock generation
    initial begin
        clk = 0;
        forever #(CLK_PERIOD/2) clk = ~clk;
    end

    // Golden reference values
    reg signed [ACC_WIDTH-1:0] golden_output [0:3][0:3];

    initial begin
        // Initialize golden outputs from Python model
""")

        # 填充 golden 值
        for i in range(4):
            for j in range(4):
                f.write(f"        golden_output[{i}][{j}] = 32'd{C[i,j]};\n")

        f.write("""
        // Initialize signals
        rst_n = 0;
        weight_in = 0;
        weight_valid = 0;
        weight_load = 0;
        input_data = 0;
        input_valid = 0;
        output_ready = 4'b0000;
        flush = 0;
        clk_enable = 1;

        repeat(5) @(posedge clk);
        rst_n = 1;
        repeat(2) @(posedge clk);

        $display("\\n========================================");
        $display("Automated Test: {test_name}");
        $display("========================================\\n");

        // Load weights
        $display("Loading weights...");
        weight_load = 1;
""")

        # 生成权重加载代码
        idx = 0
        for i in range(4):
            for j in range(4):
                f.write(f"        @(posedge clk); weight_in = 16'd{B[i,j]}; weight_valid = 1;\n")
                idx += 1

        f.write("""        weight_valid = 0;
        weight_load = 0;

        repeat(5) @(posedge clk);

        // Send inputs
        $display("Sending inputs...");
        output_ready = 4'b1111;
""")

        # 生成输入数据代码
        for i in range(4):
            for j in range(4):
                f.write(f"        @(posedge clk); input_data = 16'd{A[i,j]}; input_valid = 1;\n")

        f.write("""        input_valid = 0;

        // Wait for outputs
        repeat(50) @(posedge clk);

        // Verify outputs
        $display("\\n========================================");
        $display("Verification Results");
        $display("========================================");

        fork
            begin
                repeat(100) @(posedge clk);
            end
            begin
                wait(output_valid[0]);
                repeat(5) @(posedge clk);  // Wait for all outputs
            end
        join_any

        // Check each output
        integer i, j, errors;
        errors = 0;

        for (i = 0; i < 4; i = i + 1) begin
            for (j = 0; j < 4; j = j + 1) begin
                automatic logic [31:0] actual = output_data[i*32 +: 32];
                automatic logic [31:0] expected = golden_output[i][j];

                if (actual !== expected) begin
                    $display("❌ ERROR: C[%0d][%0d] = %0d (expected %0d)",
                             i, j, $signed(actual), $signed(expected));
                    errors = errors + 1;
                end else begin
                    $display("✅ OK: C[%0d][%0d] = %0d", i, j, $signed(actual));
                end
            end
        end

        $display("\\n========================================");
        if (errors == 0) begin
            $display("✅ TEST PASSED: All outputs match golden model");
        end else begin
            $display("❌ TEST FAILED: %0d mismatches detected", errors);
        end
        $display("========================================\\n");

        $finish;
    end

endmodule
""")

    print(f"📁 自动测试平台已生成: {filename}")

def main():
    """主测试流程"""
    print("=" * 60)
    print("Systolic Array Golden Model Verification")
    print("=" * 60)

    # 运行所有测试用例
    tests = [
        ("test1_identity", test_case_1),
        ("test2_constant", test_case_2),
        ("test3_random", test_case_3),
        ("test4_cnn", test_case_4),
    ]

    for name, test_func in tests:
        A, B, C = test_func()

        # 导出测试向量
        export_test_vectors(A, B, C, name)

        # 生成自动验证的 testbench
        generate_verilog_testbench(A, B, C, name)

    print("\n" + "=" * 60)
    print("Golden Model 验证完成")
    print("=" * 60)
    print("\n生成的文件:")
    print("  - test_vectors_*.txt: 测试向量文件")
    print("  - auto_test_*.v: 自动验证的测试平台")
    print("\n下一步:")
    print("  1. 使用测试向量进行仿真")
    print("  2. 运行自动测试平台")
    print("  3. 查看验证结果")

if __name__ == "__main__":
    main()
