ARCH_NAME := IS
ARCH_KEY := is
TB_MAIN := $(abspath $(CURDIR)/../tb/systolic_array_is_tb.v)
TB_TOP := systolic_array_is_tb
TB_WAVE := $(abspath $(CURDIR)/../tb/systolic_array_is_latency_tb.v)
TB_WAVE_TOP := systolic_array_is_latency_tb
include $(abspath $(CURDIR)/../../scripts/arch_common.mk)
