ARCH_NAME := WS
ARCH_KEY := ws
TB_MAIN := $(abspath $(CURDIR)/../tb/systolic_array_ws_tb.v)
TB_TOP := systolic_array_ws_tb
TB_WAVE := $(abspath $(CURDIR)/../tb/systolic_array_ws_latency_tb.v)
TB_WAVE_TOP := systolic_array_ws_latency_tb
include $(abspath $(CURDIR)/../../scripts/arch_common.mk)
