#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/prepare_env.sh"

ICC2_BIN="${ICC2_BIN:-icc2_shell}"
require_tool "$ICC2_BIN"

export ICC2_STEP="${1:-all}"
export DESIGN_NAME SDC_FILE ICC2_INPUT_NETLIST ICC2_DESIGN_LIB ICC2_RESULTS_DIR ICC2_REPORT_DIR ICC2_WORK_DIR
export ICC2_TECH_FILE ICC2_REFERENCE_LIBS TLUPLUS_MAX TLUPLUS_MIN TLUPLUS_MAP ICC2_OVERWRITE_LIB
export ICC2_CREATE_LIB_MODE="${ICC2_CREATE_LIB_MODE:-tech_and_ref}"
export POWER_NET GROUND_NET PLACE_SITE FLOORPLAN_ASPECT_RATIO CORE_UTILIZATION
export CORE_MARGIN_LEFT CORE_MARGIN_BOTTOM CORE_MARGIN_RIGHT CORE_MARGIN_TOP
export RING_LAYER_H RING_LAYER_V RING_WIDTH RING_SPACING RING_OFFSET
export ADD_POWER_STRIPES STRIPE_LAYER STRIPE_WIDTH STRIPE_SPACING STRIPE_SET_TO_SET_DISTANCE
export ICC2_GDS ICC2_NETLIST ICC2_SDF ICC2_DEF GDS_STREAM_OUT_MAP CLOCK_PORT CLOCK_PERIOD_NS

"$ICC2_BIN" -f "${SCRIPT_DIR}/run_icc2.tcl" | tee "$ICC2_LOG_FILE"
