proc require_env {name} {
    if {![info exists ::env($name)] || $::env($name) eq ""} {
        error "Missing environment variable '$name'"
    }
    return $::env($name)
}

proc env_or_default {name default_value} {
    if {[info exists ::env($name)] && $::env($name) ne ""} {
        return $::env($name)
    }
    return $default_value
}

proc split_paths {raw} {
    if {$raw eq ""} {
        return {}
    }
    return [split $raw]
}

proc run_or_warn {label command} {
    set rc [catch {uplevel 1 $command} result]
    if {$rc != 0} {
        puts "WARN($label): $result"
        return 0
    }
    return 1
}

proc write_mmmc_file {path lib_max lib_min qrc_file sdc_file} {
    set fh [open $path w]
    puts $fh "# Auto-generated by run_innovus.tcl"
    puts $fh "create_library_set -name lib_setup -timing [list $lib_max]"
    puts $fh "create_library_set -name lib_hold -timing [list $lib_min]"
    if {$qrc_file ne ""} {
        puts $fh "create_rc_corner -name rc_default -qx_tech_file [list $qrc_file]"
    } else {
        puts $fh "create_rc_corner -name rc_default"
    }
    puts $fh "create_delay_corner -name dc_default -late_library_set lib_setup -early_library_set lib_hold -rc_corner rc_default"
    puts $fh "create_constraint_mode -name constraint_default -sdc_files [list $sdc_file]"
    puts $fh "create_analysis_view -name view_default -constraint_mode constraint_default -delay_corner dc_default"
    puts $fh "set_analysis_view -setup {view_default} -hold {view_default}"
    close $fh
}

proc report_innovus {timing_rpt power_rpt area_rpt qor_rpt} {
    run_or_warn "report_timing" [list redirect -file $timing_rpt {report_timing}]
    run_or_warn "report_power" [list redirect -file $power_rpt {report_power}]
    if {![run_or_warn "report_area" [list redirect -file $area_rpt {report_area}]]} {
        run_or_warn "reportArea" [list redirect -file $area_rpt {reportArea}]
    }
    if {![run_or_warn "summaryReport" [list redirect -file $qor_rpt {summaryReport}]]} {
        run_or_warn "report_qor" [list redirect -file $qor_rpt {report_qor}]
    }
}

proc dbget_terms_by_direction {direction} {
    set terms [dbGet top.terms.direction $direction -p]
    if {$terms eq "0x0" || $terms eq ""} {
        return {}
    }
    return [dbGet $terms.name]
}

proc remove_from_list {items remove_items} {
    set filtered {}
    foreach item $items {
        if {[lsearch -exact $remove_items $item] < 0} {
            lappend filtered $item
        }
    }
    return $filtered
}

proc assign_top_io_pins {input_layer output_layer top_layer clock_pins pin_offset} {
    set input_pins [dbget_terms_by_direction input]
    set output_pins [dbget_terms_by_direction output]
    set inout_pins [dbget_terms_by_direction inout]
    set clock_pins_present {}
    set top_status_pins {}
    array set io_edge {
        LEFT 0
        TOP 1
        RIGHT 2
        BOTTOM 3
    }

    foreach pin $clock_pins {
        if {[lsearch -exact $input_pins $pin] >= 0} {
            lappend clock_pins_present $pin
        }
    }
    set input_pins [remove_from_list $input_pins $clock_pins_present]

    foreach pin {result_valid busy} {
        if {[lsearch -exact $output_pins $pin] >= 0} {
            lappend top_status_pins $pin
        }
    }
    set output_pins [remove_from_list $output_pins $top_status_pins]

    puts "Assigning top IO pins:"
    puts "  clock pins  = [llength $clock_pins_present]"
    puts "  input pins  = [llength $input_pins]"
    puts "  output pins = [llength $output_pins]"
    puts "  status pins = [llength $top_status_pins]"
    puts "  inout pins  = [llength $inout_pins]"

    run_or_warn "setPinAssignMode" {setPinAssignMode -pinEditInBatch true}
    if {[llength $clock_pins_present] > 0} {
        editPin -pin $clock_pins_present -edge $io_edge(BOTTOM) -layer $top_layer -spreadType CENTER -offsetStart $pin_offset -offsetEnd $pin_offset -fixedPin -fixOverlap 1 -snap TRACK -use CLOCK
    }
    if {[llength $input_pins] > 0} {
        editPin -pin $input_pins -edge $io_edge(LEFT) -layer $input_layer -spreadType SIDE -offsetStart $pin_offset -offsetEnd $pin_offset -fixedPin -fixOverlap 1 -snap TRACK -use SIGNAL
    }
    if {[llength $output_pins] > 0} {
        editPin -pin $output_pins -edge $io_edge(RIGHT) -layer $output_layer -spreadType SIDE -offsetStart $pin_offset -offsetEnd $pin_offset -fixedPin -fixOverlap 1 -snap TRACK -use SIGNAL
    }
    if {[llength $top_status_pins] > 0} {
        editPin -pin $top_status_pins -edge $io_edge(TOP) -layer $top_layer -spreadType CENTER -spacing 2 -offsetStart $pin_offset -offsetEnd $pin_offset -fixedPin -fixOverlap 1 -snap TRACK -use SIGNAL
    }
    if {[llength $inout_pins] > 0} {
        editPin -pin $inout_pins -edge $io_edge(TOP) -layer $top_layer -spreadType SIDE -offsetStart $pin_offset -offsetEnd $pin_offset -fixedPin -fixOverlap 1 -snap TRACK -use SIGNAL
    }
    run_or_warn "setPinAssignMode" {setPinAssignMode -pinEditInBatch false}
}

proc apply_lvs_pin_patch_shapes {raw_patches} {
    set count 0
    foreach raw [split $raw_patches ";"] {
        set spec [string trim $raw]
        if {$spec eq ""} {
            continue
        }
        set fields [split $spec]
        if {[llength $fields] != 7} {
            error "Invalid INNOVUS_LVS_PIN_PATCH_SHAPES item '$spec' (expected: net layer x1 y1 x2 y2 width)"
        }
        set net [lindex $fields 0]
        set layer [lindex $fields 1]
        set x1 [lindex $fields 2]
        set y1 [lindex $fields 3]
        set x2 [lindex $fields 4]
        set y2 [lindex $fields 5]
        set width [lindex $fields 6]
        puts "  patch_shape net=$net layer=$layer path=($x1,$y1)-($x2,$y2) width=$width"
        if {[catch {add_shape -net $net -layer $layer -status ROUTED -shape COREWIRE -pathSeg [list $x1 $y1 $x2 $y2] -width $width} result]} {
            error "Failed to add LVS pin patch shape '$spec': $result"
        }
        incr count
    }
    return $count
}

proc apply_lvs_pin_patch_vias {raw_patches} {
    set count 0
    foreach raw [split $raw_patches ";"] {
        set spec [string trim $raw]
        if {$spec eq ""} {
            continue
        }
        set fields [split $spec]
        if {[llength $fields] != 4} {
            error "Invalid INNOVUS_LVS_PIN_PATCH_VIAS item '$spec' (expected: net via x y)"
        }
        set net [lindex $fields 0]
        set via [lindex $fields 1]
        set x [lindex $fields 2]
        set y [lindex $fields 3]
        puts "  patch_via net=$net via=$via pt=($x,$y)"
        if {[catch {add_via -net $net -via $via -pt [list $x $y]} result]} {
            error "Failed to add LVS pin patch via '$spec': $result"
        }
        incr count
    }
    return $count
}

proc apply_lvs_pin_patch_labels {raw_patches} {
    set count 0
    foreach raw [split $raw_patches ";"] {
        set spec [string trim $raw]
        if {$spec eq ""} {
            continue
        }
        set fields [split $spec]
        if {[llength $fields] < 4 || [llength $fields] > 5} {
            error "Invalid INNOVUS_LVS_PIN_PATCH_LABELS item '$spec' (expected: label layer x y [height])"
        }
        set label [lindex $fields 0]
        set layer [lindex $fields 1]
        set x [lindex $fields 2]
        set y [lindex $fields 3]
        set height "0.08"
        if {[llength $fields] == 5} {
            set height [lindex $fields 4]
        }
        puts "  patch_label label=$label layer=$layer pt=($x,$y) height=$height"
        if {[catch {add_text -label $label -layer $layer -pt [list $x $y] -height $height} result]} {
            error "Failed to add LVS pin patch label '$spec': $result"
        }
        incr count
    }
    return $count
}

proc apply_lvs_pin_patches {shape_specs via_specs label_specs} {
    if {$shape_specs eq "" && $via_specs eq "" && $label_specs eq ""} {
        return
    }

    puts "Applying LVS pin-access patches:"
    set shape_count [apply_lvs_pin_patch_shapes $shape_specs]
    set via_count [apply_lvs_pin_patch_vias $via_specs]
    set label_count [apply_lvs_pin_patch_labels $label_specs]
    puts "  patch_shapes = $shape_count"
    puts "  patch_vias   = $via_count"
    puts "  patch_labels = $label_count"

    run_or_warn "verifyConnectivity-lvs-pin-patches" [list redirect -file [require_env INNOVUS_CONNECTIVITY_RPT] {verifyConnectivity}]
    run_or_warn "verify_drc-lvs-pin-patches" [list redirect -file [require_env INNOVUS_DRC_RPT] {verify_drc}]
    run_or_warn "extractRC-lvs-pin-patches" {extractRC}
}

set step [string tolower [require_env INNOVUS_STEP]]
set gui_mode [expr {[env_or_default INNOVUS_GUI "0"] eq "1"}]
set design_name [require_env DESIGN_NAME]
set input_netlist [require_env INNOVUS_INPUT_NETLIST]
set tech_lef [require_env INNOVUS_TECH_LEF]
set lef_files [split_paths [require_env INNOVUS_LEF_FILES]]
set lib_max [require_env INNOVUS_LIB_MAX]
set lib_min [require_env INNOVUS_LIB_MIN]
set qrc_file [env_or_default INNOVUS_QRC_TECH_FILE ""]
set sdc_file [require_env SDC_FILE]
set mmmc_file [require_env INNOVUS_MMMC_FILE]
set checkpoint_prefix [require_env INNOVUS_CHECKPOINT_PREFIX]
set power_net [require_env POWER_NET]
set ground_net [require_env GROUND_NET]
set ring_layer_h [require_env RING_LAYER_H]
set ring_layer_v [require_env RING_LAYER_V]
set ring_width [require_env RING_WIDTH]
set ring_spacing [require_env RING_SPACING]
set ring_offset [require_env RING_OFFSET]
set add_power_stripes [env_or_default ADD_POWER_STRIPES "0"]
set stripe_layer [env_or_default STRIPE_LAYER ""]
set stripe_width [env_or_default STRIPE_WIDTH "0.0"]
set stripe_spacing [env_or_default STRIPE_SPACING "0.0"]
set stripe_distance [env_or_default STRIPE_SET_TO_SET_DISTANCE "0.0"]
set gds_map [env_or_default INNOVUS_GDS_MAP ""]
set gds_units [env_or_default INNOVUS_GDS_UNITS "1000"]
set gds_snap_to_mgrid [env_or_default INNOVUS_GDS_SNAP_TO_MGRID "0"]
set gds_support_path_type4 [env_or_default INNOVUS_GDS_SUPPORT_PATH_TYPE4 ""]
set gds_label_all_pin_shapes [env_or_default INNOVUS_GDS_LABEL_ALL_PIN_SHAPES "0"]
set gds_attach_net_name [env_or_default INNOVUS_GDS_ATTACH_NET_NAME ""]
set gds_attach_instance_name [env_or_default INNOVUS_GDS_ATTACH_INSTANCE_NAME ""]
set gds_merge_files [split [env_or_default INNOVUS_GDS_MERGE_FILES ""]]
set process_node [env_or_default INNOVUS_PROCESS_NODE "28"]
set io_input_layer [env_or_default INNOVUS_IO_INPUT_LAYER "M2"]
set io_output_layer [env_or_default INNOVUS_IO_OUTPUT_LAYER "M2"]
set io_top_layer [env_or_default INNOVUS_IO_TOP_LAYER "M3"]
set clock_pin_list [split_paths [env_or_default INNOVUS_CLOCK_PINS "clk"]]
set io_pin_offset [env_or_default INNOVUS_IO_PIN_OFFSET "5.0"]
set add_well_taps [env_or_default INNOVUS_ADD_WELL_TAPS "0"]
set tap_cell [env_or_default INNOVUS_TAP_CELL ""]
set tap_cell_interval [env_or_default INNOVUS_TAP_CELL_INTERVAL "20"]
set tap_in_row_offset [env_or_default INNOVUS_TAP_IN_ROW_OFFSET "10"]
set add_endcaps [env_or_default INNOVUS_ADD_ENDCAPS "0"]
set endcap_left_cell [env_or_default INNOVUS_ENDCAP_LEFT_CELL ""]
set endcap_right_cell [env_or_default INNOVUS_ENDCAP_RIGHT_CELL ""]
set add_fillers [env_or_default INNOVUS_ADD_FILLERS "0"]
set filler_cells [split_paths [env_or_default INNOVUS_FILLER_CELLS ""]]
set nanoroute_via_weight [env_or_default INNOVUS_NANOROUTE_VIA_WEIGHT ""]
set lvs_pin_patch_shapes [env_or_default INNOVUS_LVS_PIN_PATCH_SHAPES ""]
set lvs_pin_patch_vias [env_or_default INNOVUS_LVS_PIN_PATCH_VIAS ""]
set lvs_pin_patch_labels [env_or_default INNOVUS_LVS_PIN_PATCH_LABELS ""]

switch -- $step {
    init {
        set run_init 1
        set run_place 0
        set run_cts 0
        set run_route 0
        set run_export 0
        set restore_route_checkpoint 0
    }
    place {
        set run_init 1
        set run_place 1
        set run_cts 0
        set run_route 0
        set run_export 0
        set restore_route_checkpoint 0
    }
    cts {
        set run_init 1
        set run_place 1
        set run_cts 1
        set run_route 0
        set run_export 0
        set restore_route_checkpoint 0
    }
    route {
        set run_init 1
        set run_place 1
        set run_cts 1
        set run_route 1
        set run_export 0
        set restore_route_checkpoint 0
    }
    export {
        set run_init 0
        set run_place 0
        set run_cts 0
        set run_route 0
        set run_export 1
        set restore_route_checkpoint 1
    }
    all {
        set run_init 1
        set run_place 1
        set run_cts 1
        set run_route 1
        set run_export 1
        set restore_route_checkpoint 0
    }
    default {
        error "Unsupported INNOVUS_STEP '$step' (expected init, place, cts, route, export, or all)"
    }
}

file mkdir [file dirname $mmmc_file]
write_mmmc_file $mmmc_file $lib_max $lib_min $qrc_file $sdc_file

set init_lef_file [concat [list $tech_lef] $lef_files]
set init_verilog $input_netlist
set init_top_cell $design_name
set init_design_settop 1
set init_pwr_net [list $power_net]
set init_gnd_net [list $ground_net]
set init_mmmc_file $mmmc_file

puts "Innovus setup:"
puts "  design_name = $design_name"
puts "  input_netlist = $input_netlist"
puts "  tech_lef = $tech_lef"
puts "  lef_files = $lef_files"
puts "  mmmc_file = $mmmc_file"
puts "  step = $step"
puts "  gds_map = $gds_map"
puts "  gds_units = $gds_units"
puts "  gds_snap_to_mgrid = $gds_snap_to_mgrid"
puts "  gds_support_path_type4 = $gds_support_path_type4"
puts "  gds_label_all_pin_shapes = $gds_label_all_pin_shapes"
puts "  gds_attach_net_name = $gds_attach_net_name"
puts "  gds_attach_instance_name = $gds_attach_instance_name"
puts "  gds_merge_files = $gds_merge_files"
puts "  tap_cell = $tap_cell"
puts "  endcap_cells = $endcap_left_cell $endcap_right_cell"
puts "  filler_cells = $filler_cells"
puts "  nanoroute_via_weight = $nanoroute_via_weight"
puts "  lvs_pin_patch_shapes = $lvs_pin_patch_shapes"
puts "  lvs_pin_patch_vias = $lvs_pin_patch_vias"
puts "  lvs_pin_patch_labels = $lvs_pin_patch_labels"

if {$restore_route_checkpoint} {
    set route_checkpoint "${checkpoint_prefix}_route.enc.dat"
    if {![file exists $route_checkpoint]} {
        set route_checkpoint "${checkpoint_prefix}_route.enc"
    }
    if {![file exists $route_checkpoint]} {
        error "Innovus route checkpoint not found for export: ${checkpoint_prefix}_route.enc.dat"
    }
    puts "Restoring route checkpoint for export:"
    puts "  checkpoint = $route_checkpoint"
    restoreDesign $route_checkpoint $design_name
} else {
    init_design
    run_or_warn "setDesignMode-process" [list setDesignMode -process $process_node]
    run_or_warn "setDelayCalMode-siAware" {setDelayCalMode -siAware false}
}

if {$run_init} {
    floorPlan \
        -r [require_env FLOORPLAN_ASPECT_RATIO] \
        [require_env CORE_UTILIZATION] \
        [require_env CORE_MARGIN_LEFT] \
        [require_env CORE_MARGIN_BOTTOM] \
        [require_env CORE_MARGIN_RIGHT] \
        [require_env CORE_MARGIN_TOP]

    assign_top_io_pins $io_input_layer $io_output_layer $io_top_layer $clock_pin_list $io_pin_offset
    run_or_warn "checkPinAssignment" [list redirect -file [require_env INNOVUS_PIN_ASSIGN_RPT] {checkPinAssignment -report_violating_pin}]

    run_or_warn "clearGlobalNets" {clearGlobalNets}
    run_or_warn "globalNetConnect-power" [list globalNetConnect $power_net -type pgpin -pin $power_net -all]
    run_or_warn "globalNetConnect-ground" [list globalNetConnect $ground_net -type pgpin -pin $ground_net -all]
    run_or_warn "globalNetConnect-tiehi" [list globalNetConnect $power_net -type tiehi -all]
    run_or_warn "globalNetConnect-tielo" [list globalNetConnect $ground_net -type tielo -all]

    if {$add_endcaps eq "1" && $endcap_left_cell ne "" && $endcap_right_cell ne ""} {
        run_or_warn "setEndCapMode-reset" {setEndCapMode -reset}
        run_or_warn "setEndCapMode" [list setEndCapMode -leftEdge $endcap_left_cell -rightEdge $endcap_right_cell -prefix ENDCAP]
        run_or_warn "addEndCap" {addEndCap -prefix ENDCAP}
    }

    if {$add_well_taps eq "1" && $tap_cell ne ""} {
        run_or_warn "addWellTap" [list addWellTap \
            -cell $tap_cell \
            -cellInterval $tap_cell_interval \
            -inRowOffset $tap_in_row_offset \
            -prefix WELLTAP]
    }

    run_or_warn "addRing" [list addRing \
        -nets [list $power_net $ground_net] \
        -type core_rings \
        -follow core \
        -layer [list top $ring_layer_h bottom $ring_layer_h left $ring_layer_v right $ring_layer_v] \
        -width [list top $ring_width bottom $ring_width left $ring_width right $ring_width] \
        -spacing [list top $ring_spacing bottom $ring_spacing left $ring_spacing right $ring_spacing] \
        -offset [list top $ring_offset bottom $ring_offset left $ring_offset right $ring_offset]]

    if {$add_power_stripes eq "1" && $stripe_layer ne ""} {
        run_or_warn "addStripe" [list addStripe \
            -nets [list $power_net $ground_net] \
            -layer $stripe_layer \
            -direction vertical \
            -width $stripe_width \
            -spacing $stripe_spacing \
            -set_to_set_distance $stripe_distance]
    }

    run_or_warn "sroute" [list sroute -nets [list $power_net $ground_net] -connect {corePin padPin blockPin} -allowLayerChange 1]
    run_or_warn "saveDesign-init" [list saveDesign "${checkpoint_prefix}_init.enc"]
}

if {$run_place} {
    placeDesign
    run_or_warn "optDesign-preCTS" {optDesign -preCTS}
    run_or_warn "saveDesign-place" [list saveDesign "${checkpoint_prefix}_place.enc"]
}

if {$run_cts} {
    set cts_buffer_list [env_or_default CTS_BUFFER_LIST ""]
    if {$cts_buffer_list ne ""} {
        run_or_warn "set_ccopt_property" [list set_ccopt_property buffer_cells [split_paths $cts_buffer_list]]
    }
    ccopt_design
    run_or_warn "optDesign-postCTS" {optDesign -postCTS}
    run_or_warn "saveDesign-cts" [list saveDesign "${checkpoint_prefix}_cts.enc"]
}

if {$run_route} {
    if {$nanoroute_via_weight ne ""} {
        run_or_warn "setNanoRouteMode-dfm-via-weight" [list setNanoRouteMode -dbViaWeight $nanoroute_via_weight]
    }
    run_or_warn "setNanoRouteMode-spread" {setNanoRouteMode -droutePostRouteSpreadWire false}
    routeDesign
    run_or_warn "verifyConnectivity-route" [list redirect -file [require_env INNOVUS_CONNECTIVITY_RPT] {verifyConnectivity}]
    run_or_warn "verify_drc-route" [list redirect -file [require_env INNOVUS_DRC_RPT] {verify_drc}]
    run_or_warn "checkRoute-route" [list redirect -file [require_env INNOVUS_ROUTE_RPT] {checkRoute}]
    run_or_warn "setDelayCalMode-siAware" {setDelayCalMode -siAware false}
    run_or_warn "optDesign-postRoute" {optDesign -postRoute}
    run_or_warn "extractRC" {extractRC}

    if {$add_fillers eq "1" && [llength $filler_cells] > 0} {
        run_or_warn "addFiller" [list addFiller \
            -cell $filler_cells \
            -prefix FILLER \
            -fitGap \
            -markFixed]
        run_or_warn "verifyConnectivity-postfill" [list redirect -file [require_env INNOVUS_CONNECTIVITY_RPT] {verifyConnectivity}]
        run_or_warn "verify_drc-postfill" [list redirect -file [require_env INNOVUS_DRC_RPT] {verify_drc}]
        run_or_warn "checkRoute-postfill" [list redirect -file [require_env INNOVUS_ROUTE_RPT] {checkRoute}]
        run_or_warn "extractRC-postfill" {extractRC}
    }

    run_or_warn "saveDesign-route" [list saveDesign "${checkpoint_prefix}_route.enc"]
}

report_innovus [require_env INNOVUS_TIMING_RPT] [require_env INNOVUS_POWER_RPT] [require_env INNOVUS_AREA_RPT] [require_env INNOVUS_QOR_RPT]

if {$run_export} {
    apply_lvs_pin_patches $lvs_pin_patch_shapes $lvs_pin_patch_vias $lvs_pin_patch_labels
    saveNetlist [require_env INNOVUS_NETLIST]
    saveNetlist [require_env INNOVUS_LVS_NETLIST] -phys -excludeLeafCell
    write_sdf [require_env INNOVUS_SDF]
    defOut [require_env INNOVUS_DEF]
    if {$gds_snap_to_mgrid eq "1" || [string tolower $gds_snap_to_mgrid] eq "true"} {
        run_or_warn "setStreamOutMode-snapToMGrid" {setStreamOutMode -snapToMGrid true}
    }
    if {$gds_support_path_type4 ne ""} {
        run_or_warn "setStreamOutMode-supportPathType4" [list setStreamOutMode -supportPathType4 $gds_support_path_type4]
    }
    if {$gds_label_all_pin_shapes eq "1" || [string tolower $gds_label_all_pin_shapes] eq "true"} {
        run_or_warn "setStreamOutMode-labelAllPinShape" {setStreamOutMode -labelAllPinShape true}
    }
    set stream_args [list [require_env INNOVUS_GDS] -units $gds_units -mode ALL]
    if {$gds_map ne ""} {
        lappend stream_args -mapFile $gds_map
    }
    if {$gds_attach_net_name ne ""} {
        lappend stream_args -attachNetName $gds_attach_net_name
    }
    if {$gds_attach_instance_name ne ""} {
        lappend stream_args -attachInstanceName $gds_attach_instance_name
    }
    if {[llength $gds_merge_files] > 0} {
        lappend stream_args -merge $gds_merge_files
    }
    if {[llength $gds_merge_files] > 0 && $gds_map ne ""} {
        streamOut {*}$stream_args
    } elseif {[llength $gds_merge_files] > 0} {
        streamOut {*}$stream_args
    } elseif {$gds_map ne ""} {
        streamOut {*}$stream_args
    } else {
        streamOut {*}$stream_args
    }
    run_or_warn "saveDesign-export" [list saveDesign "${checkpoint_prefix}_export.enc"]
}

if {!$gui_mode} {
    exit
}
