#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/prepare_env.sh"

INNOVUS_BIN="${INNOVUS_BIN:-innovus}"
require_tool "$INNOVUS_BIN"

export INNOVUS_STEP="${1:-all}"
export INNOVUS_GUI="${INNOVUS_GUI:-0}"

export DESIGN_NAME SDC_FILE CLOCK_PORT CLOCK_PERIOD_NS
export INNOVUS_INPUT_NETLIST INNOVUS_WORK_DIR INNOVUS_REPORT_DIR INNOVUS_RESULTS_DIR INNOVUS_LOG_FILE
export INNOVUS_TECH_LEF INNOVUS_LEF_FILES INNOVUS_LIB_MAX INNOVUS_LIB_MIN INNOVUS_QRC_TECH_FILE INNOVUS_GDS_MAP
export INNOVUS_MMMC_FILE INNOVUS_CHECKPOINT_PREFIX INNOVUS_TIMING_RPT INNOVUS_POWER_RPT INNOVUS_AREA_RPT INNOVUS_QOR_RPT
export INNOVUS_NETLIST INNOVUS_SDF INNOVUS_DEF INNOVUS_GDS
export POWER_NET GROUND_NET PLACE_SITE FLOORPLAN_ASPECT_RATIO CORE_UTILIZATION
export CORE_MARGIN_LEFT CORE_MARGIN_BOTTOM CORE_MARGIN_RIGHT CORE_MARGIN_TOP
export RING_LAYER_H RING_LAYER_V RING_WIDTH RING_SPACING RING_OFFSET
export ADD_POWER_STRIPES STRIPE_LAYER STRIPE_WIDTH STRIPE_SPACING STRIPE_SET_TO_SET_DISTANCE CTS_BUFFER_LIST

exec "$INNOVUS_BIN" -nowin -overwrite -init "${SCRIPT_DIR}/run_innovus.tcl" -log "$INNOVUS_LOG_FILE"
