#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(builtin cd "$(dirname "${BASH_SOURCE[0]}")" && /bin/pwd -P)
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/prepare_env.sh"

INNOVUS_BIN="${INNOVUS_BIN:-innovus}"
require_tool "$INNOVUS_BIN"

export INNOVUS_STEP="${1:-all}"
export INNOVUS_GUI="${INNOVUS_GUI:-0}"

export DESIGN_NAME SDC_FILE CLOCK_PORT CLOCK_PERIOD_NS
export INNOVUS_INPUT_NETLIST INNOVUS_WORK_DIR INNOVUS_REPORT_DIR INNOVUS_RESULTS_DIR INNOVUS_LOG_FILE
export INNOVUS_TECH_LEF INNOVUS_LEF_FILES INNOVUS_LIB_MAX INNOVUS_LIB_MIN INNOVUS_QRC_TECH_FILE
export INNOVUS_GDS_MAP INNOVUS_GDS_MERGE_FILES INNOVUS_GDS_UNITS INNOVUS_GDS_SNAP_TO_MGRID INNOVUS_GDS_SUPPORT_PATH_TYPE4
export INNOVUS_PATCH_VIA_METALS INNOVUS_VIA_METAL_PATCH_TLEF INNOVUS_VIA_METAL_PATCH_ENC_DBU INNOVUS_VIA_METAL_PATCH_GENERIC INNOVUS_REMAP_GDS_DATATYPES
export INNOVUS_NANOROUTE_VIA_WEIGHT
export INNOVUS_PROCESS_NODE INNOVUS_IO_INPUT_LAYER INNOVUS_IO_OUTPUT_LAYER INNOVUS_IO_TOP_LAYER INNOVUS_CLOCK_PINS INNOVUS_IO_PIN_OFFSET
export INNOVUS_ADD_WELL_TAPS INNOVUS_TAP_CELL INNOVUS_TAP_CELL_INTERVAL INNOVUS_TAP_IN_ROW_OFFSET
export INNOVUS_ADD_ENDCAPS INNOVUS_ENDCAP_LEFT_CELL INNOVUS_ENDCAP_RIGHT_CELL
export INNOVUS_ADD_FILLERS INNOVUS_FILLER_CELLS
export INNOVUS_LVS_PIN_PATCH_SHAPES INNOVUS_LVS_PIN_PATCH_VIAS INNOVUS_LVS_PIN_PATCH_LABELS
export INNOVUS_MMMC_FILE INNOVUS_CHECKPOINT_PREFIX INNOVUS_TIMING_RPT INNOVUS_POWER_RPT INNOVUS_AREA_RPT INNOVUS_QOR_RPT
export INNOVUS_PIN_ASSIGN_RPT INNOVUS_CONNECTIVITY_RPT INNOVUS_DRC_RPT INNOVUS_ROUTE_RPT
export INNOVUS_NETLIST INNOVUS_LVS_NETLIST INNOVUS_SDF INNOVUS_DEF INNOVUS_GDS
export INNOVUS_GDS_UNPATCHED INNOVUS_GDS_PATCH_MANIFEST
export POWER_NET GROUND_NET PLACE_SITE FLOORPLAN_ASPECT_RATIO CORE_UTILIZATION
export CORE_MARGIN_LEFT CORE_MARGIN_BOTTOM CORE_MARGIN_RIGHT CORE_MARGIN_TOP
export RING_LAYER_H RING_LAYER_V RING_WIDTH RING_SPACING RING_OFFSET
export ADD_POWER_STRIPES STRIPE_LAYER STRIPE_WIDTH STRIPE_SPACING STRIPE_SET_TO_SET_DISTANCE CTS_BUFFER_LIST

"$INNOVUS_BIN" -nowin -overwrite -init "${SCRIPT_DIR}/run_innovus.tcl" -log "$INNOVUS_LOG_FILE"

if [[ "${INNOVUS_ALLOW_LOG_ERRORS:-0}" != "1" ]] && grep -E '^\*\*ERROR:|\*\*ERROR:|ERROR \(' "$INNOVUS_LOG_FILE" >/dev/null 2>&1; then
    echo "[dip-flow][ERROR] Innovus log contains errors; see ${INNOVUS_LOG_FILE}" >&2
    exit 1
fi

case "$INNOVUS_STEP" in
    all|export)
        if [[ "${INNOVUS_PATCH_VIA_METALS:-0}" == "1" ]]; then
            require_tool "${CALIBREDRV_BIN:-calibredrv}"
            patch_args=()
            if [[ "${INNOVUS_VIA_METAL_PATCH_GENERIC:-1}" != "1" ]]; then
                patch_args+=(--no-generic)
            fi
            if [[ "${INNOVUS_REMAP_GDS_DATATYPES:-1}" != "1" ]]; then
                patch_args+=(--no-remap-datatypes)
            fi
            python3 "${SCRIPT_DIR}/patch_gds_via_metals.py" \
                --gds "$INNOVUS_GDS" \
                --tlef "$INNOVUS_VIA_METAL_PATCH_TLEF" \
                --stream-map "$INNOVUS_GDS_MAP" \
                --backup "$INNOVUS_GDS_UNPATCHED" \
                --backup-manifest "$INNOVUS_GDS_PATCH_MANIFEST" \
                --calibredrv "${CALIBREDRV_BIN:-calibredrv}" \
                --generic-enclosure-dbu "$INNOVUS_VIA_METAL_PATCH_ENC_DBU" \
                --work-dir "$INNOVUS_WORK_DIR" \
                "${patch_args[@]}"
        fi
        ;;
esac
