proc require_env {name} {
    if {![info exists ::env($name)] || $::env($name) eq ""} {
        error "Missing environment variable '$name'"
    }
    return $::env($name)
}

proc env_or_default {name default_value} {
    if {[info exists ::env($name)] && $::env($name) ne ""} {
        return $::env($name)
    }
    return $default_value
}

proc split_paths {raw} {
    if {$raw eq ""} {
        return {}
    }
    return [split $raw]
}

proc run_or_warn {label command} {
    set rc [catch {uplevel 1 $command} result]
    if {$rc != 0} {
        puts "WARN($label): $result"
        return 0
    }
    return 1
}

proc write_mmmc_file {path lib_max lib_min qrc_file sdc_file} {
    set fh [open $path w]
    puts $fh "# Auto-generated by run_innovus.tcl"
    puts $fh "create_library_set -name lib_setup -timing [list $lib_max]"
    puts $fh "create_library_set -name lib_hold -timing [list $lib_min]"
    if {$qrc_file ne ""} {
        puts $fh "create_rc_corner -name rc_default -qx_tech_file [list $qrc_file]"
    } else {
        puts $fh "create_rc_corner -name rc_default"
    }
    puts $fh "create_delay_corner -name dc_default -late_library_set lib_setup -early_library_set lib_hold -rc_corner rc_default"
    puts $fh "create_constraint_mode -name constraint_default -sdc_files [list $sdc_file]"
    puts $fh "create_analysis_view -name view_default -constraint_mode constraint_default -delay_corner dc_default"
    puts $fh "set_analysis_view -setup {view_default} -hold {view_default}"
    close $fh
}

proc report_innovus {timing_rpt power_rpt area_rpt qor_rpt} {
    run_or_warn "report_timing" [list redirect -file $timing_rpt {report_timing}]
    run_or_warn "report_power" [list redirect -file $power_rpt {report_power}]
    if {![run_or_warn "report_area" [list redirect -file $area_rpt {report_area}]]} {
        run_or_warn "reportArea" [list redirect -file $area_rpt {reportArea}]
    }
    if {![run_or_warn "summaryReport" [list redirect -file $qor_rpt {summaryReport}]]} {
        run_or_warn "report_qor" [list redirect -file $qor_rpt {report_qor}]
    }
}

set step [string tolower [require_env INNOVUS_STEP]]
set gui_mode [expr {[env_or_default INNOVUS_GUI "0"] eq "1"}]
set design_name [require_env DESIGN_NAME]
set input_netlist [require_env INNOVUS_INPUT_NETLIST]
set tech_lef [require_env INNOVUS_TECH_LEF]
set lef_files [split_paths [require_env INNOVUS_LEF_FILES]]
set lib_max [require_env INNOVUS_LIB_MAX]
set lib_min [require_env INNOVUS_LIB_MIN]
set qrc_file [env_or_default INNOVUS_QRC_TECH_FILE ""]
set sdc_file [require_env SDC_FILE]
set mmmc_file [require_env INNOVUS_MMMC_FILE]
set checkpoint_prefix [require_env INNOVUS_CHECKPOINT_PREFIX]
set power_net [require_env POWER_NET]
set ground_net [require_env GROUND_NET]
set ring_layer_h [require_env RING_LAYER_H]
set ring_layer_v [require_env RING_LAYER_V]
set ring_width [require_env RING_WIDTH]
set ring_spacing [require_env RING_SPACING]
set ring_offset [require_env RING_OFFSET]
set add_power_stripes [env_or_default ADD_POWER_STRIPES "0"]
set stripe_layer [env_or_default STRIPE_LAYER ""]
set stripe_width [env_or_default STRIPE_WIDTH "0.0"]
set stripe_spacing [env_or_default STRIPE_SPACING "0.0"]
set stripe_distance [env_or_default STRIPE_SET_TO_SET_DISTANCE "0.0"]
set gds_map [env_or_default INNOVUS_GDS_MAP ""]

switch -- $step {
    init {
        set run_init 1
        set run_place 0
        set run_cts 0
        set run_route 0
        set run_export 0
    }
    place {
        set run_init 1
        set run_place 1
        set run_cts 0
        set run_route 0
        set run_export 0
    }
    cts {
        set run_init 1
        set run_place 1
        set run_cts 1
        set run_route 0
        set run_export 0
    }
    route {
        set run_init 1
        set run_place 1
        set run_cts 1
        set run_route 1
        set run_export 0
    }
    export -
    all {
        set run_init 1
        set run_place 1
        set run_cts 1
        set run_route 1
        set run_export 1
    }
    default {
        error "Unsupported INNOVUS_STEP '$step' (expected init, place, cts, route, export, or all)"
    }
}

file mkdir [file dirname $mmmc_file]
write_mmmc_file $mmmc_file $lib_max $lib_min $qrc_file $sdc_file

set init_lef_file [concat [list $tech_lef] $lef_files]
set init_verilog $input_netlist
set init_top_cell $design_name
set init_design_settop 1
set init_pwr_net [list $power_net]
set init_gnd_net [list $ground_net]
set init_mmmc_file $mmmc_file

puts "Innovus setup:"
puts "  design_name = $design_name"
puts "  input_netlist = $input_netlist"
puts "  tech_lef = $tech_lef"
puts "  lef_files = $lef_files"
puts "  mmmc_file = $mmmc_file"
puts "  step = $step"

init_design

if {$run_init} {
    floorPlan \
        -r [require_env FLOORPLAN_ASPECT_RATIO] \
        [require_env CORE_UTILIZATION] \
        [require_env CORE_MARGIN_LEFT] \
        [require_env CORE_MARGIN_BOTTOM] \
        [require_env CORE_MARGIN_RIGHT] \
        [require_env CORE_MARGIN_TOP]

    run_or_warn "clearGlobalNets" {clearGlobalNets}
    run_or_warn "globalNetConnect-power" [list globalNetConnect $power_net -type pgpin -pin $power_net -all]
    run_or_warn "globalNetConnect-ground" [list globalNetConnect $ground_net -type pgpin -pin $ground_net -all]
    run_or_warn "globalNetConnect-tiehi" [list globalNetConnect $power_net -type tiehi -all]
    run_or_warn "globalNetConnect-tielo" [list globalNetConnect $ground_net -type tielo -all]

    run_or_warn "addRing" [list addRing \
        -nets [list $power_net $ground_net] \
        -type core_rings \
        -follow core \
        -layer [list top $ring_layer_h bottom $ring_layer_h left $ring_layer_v right $ring_layer_v] \
        -width [list top $ring_width bottom $ring_width left $ring_width right $ring_width] \
        -spacing [list top $ring_spacing bottom $ring_spacing left $ring_spacing right $ring_spacing] \
        -offset [list top $ring_offset bottom $ring_offset left $ring_offset right $ring_offset]]

    if {$add_power_stripes eq "1" && $stripe_layer ne ""} {
        run_or_warn "addStripe" [list addStripe \
            -nets [list $power_net $ground_net] \
            -layer $stripe_layer \
            -direction vertical \
            -width $stripe_width \
            -spacing $stripe_spacing \
            -set_to_set_distance $stripe_distance]
    }

    run_or_warn "sroute" [list sroute -nets [list $power_net $ground_net] -connect {corePin padPin blockPin} -allowLayerChange 1]
    run_or_warn "saveDesign-init" [list saveDesign "${checkpoint_prefix}_init.enc"]
}

if {$run_place} {
    placeDesign
    run_or_warn "optDesign-preCTS" {optDesign -preCTS}
    run_or_warn "saveDesign-place" [list saveDesign "${checkpoint_prefix}_place.enc"]
}

if {$run_cts} {
    set cts_buffer_list [env_or_default CTS_BUFFER_LIST ""]
    if {$cts_buffer_list ne ""} {
        run_or_warn "set_ccopt_property" [list set_ccopt_property buffer_cells [split_paths $cts_buffer_list]]
    }
    ccopt_design
    run_or_warn "optDesign-postCTS" {optDesign -postCTS}
    run_or_warn "saveDesign-cts" [list saveDesign "${checkpoint_prefix}_cts.enc"]
}

if {$run_route} {
    routeDesign
    run_or_warn "optDesign-postRoute" {optDesign -postRoute}
    run_or_warn "extractRC" {extractRC}
    run_or_warn "saveDesign-route" [list saveDesign "${checkpoint_prefix}_route.enc"]
}

report_innovus [require_env INNOVUS_TIMING_RPT] [require_env INNOVUS_POWER_RPT] [require_env INNOVUS_AREA_RPT] [require_env INNOVUS_QOR_RPT]

if {$run_export} {
    saveNetlist [require_env INNOVUS_NETLIST]
    write_sdf [require_env INNOVUS_SDF]
    defOut [require_env INNOVUS_DEF]
    if {$gds_map ne ""} {
        streamOut [require_env INNOVUS_GDS] -mapFile $gds_map -mode ALL
    } else {
        streamOut [require_env INNOVUS_GDS] -mode ALL
    }
    run_or_warn "saveDesign-export" [list saveDesign "${checkpoint_prefix}_export.enc"]
}

if {!$gui_mode} {
    exit
}
