create_clock -name clk -period 10.000 [get_ports clk]
set_clock_uncertainty 0.100 [get_clocks clk]

set_input_delay -clock clk -max 2.000 [get_ports input_data]
set_input_delay -clock clk -min 0.500 [get_ports input_data]
set_input_delay -clock clk -max 2.000 [get_ports weight_in]
set_input_delay -clock clk -min 0.500 [get_ports weight_in]
set_input_delay -clock clk -max 2.000 [get_ports weight_addr*]
set_input_delay -clock clk -min 0.500 [get_ports weight_addr*]
set_input_delay -clock clk -max 2.000 [get_ports input_row_sel*]
set_input_delay -clock clk -min 0.500 [get_ports input_row_sel*]
set_input_delay -clock clk -max 2.000 [get_ports {input_valid weight_valid weight_load flush clk_enable}]
set_input_delay -clock clk -min 0.500 [get_ports {input_valid weight_valid weight_load flush clk_enable}]
set_input_delay -clock clk -max 2.000 [get_ports output_ready*]
set_input_delay -clock clk -min 0.500 [get_ports output_ready*]

set_output_delay -clock clk -max 2.000 [get_ports output_data*]
set_output_delay -clock clk -min 0.500 [get_ports output_data*]
set_output_delay -clock clk -max 2.000 [get_ports output_valid*]
set_output_delay -clock clk -min 0.500 [get_ports output_valid*]
set_output_delay -clock clk -max 2.000 [get_ports {input_ready weight_ready busy}]
set_output_delay -clock clk -min 0.500 [get_ports {input_ready weight_ready busy}]

set_false_path -from [get_ports rst_n]
