// Auto-generated test vectors for WS architecture
// Generated by golden_model.py

// Test 1: identity_matrix - All inputs and weights are 1
// Input matrix:
localparam [15:0] TEST1_INPUT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Weight matrix:
localparam [15:0] TEST1_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST1_EXPECTED [0:15] = '{32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4};

// Test 2: constant_matrix - Input=3, Weight=2
// Input matrix:
localparam [15:0] TEST2_INPUT [0:15] = '{16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3};
// Weight matrix:
localparam [15:0] TEST2_WEIGHT [0:15] = '{16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2};
// Expected output:
localparam [31:0] TEST2_EXPECTED [0:15] = '{32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24, 32'd24};

// Test 3: zero_value - Input=0, Weight=5
// Input matrix:
localparam [15:0] TEST3_INPUT [0:15] = '{16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0};
// Weight matrix:
localparam [15:0] TEST3_WEIGHT [0:15] = '{16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5};
// Expected output:
localparam [31:0] TEST3_EXPECTED [0:15] = '{32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0};

// Test 4: minimum_value - Input=1, Weight=1
// Input matrix:
localparam [15:0] TEST4_INPUT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Weight matrix:
localparam [15:0] TEST4_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST4_EXPECTED [0:15] = '{32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4, 32'd4};

// Test 5: mixed_boundary - Mixed boundary values (0, 1, 255)
// Input matrix:
localparam [15:0] TEST5_INPUT [0:15] = '{16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1};
// Weight matrix:
localparam [15:0] TEST5_WEIGHT [0:15] = '{16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0};
// Expected output:
localparam [31:0] TEST5_EXPECTED [0:15] = '{32'd255, 32'd510, 32'd-509, 32'd255, 32'd-510, 32'd255, 32'd255, 32'd-510, 32'd255, 32'd-1021, 32'd510, 32'd255, 32'd255, 32'd510, 32'd-509, 32'd255};

// Test 6: extreme_max - Input=255, Weight=255
// Input matrix:
localparam [15:0] TEST6_INPUT [0:15] = '{16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255};
// Weight matrix:
localparam [15:0] TEST6_WEIGHT [0:15] = '{16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255};
// Expected output:
localparam [31:0] TEST6_EXPECTED [0:15] = '{32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044, 32'd-2044};

// Test 7: large_accumulation - Input=100, Weight=100
// Input matrix:
localparam [15:0] TEST7_INPUT [0:15] = '{16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100};
// Weight matrix:
localparam [15:0] TEST7_WEIGHT [0:15] = '{16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100};
// Expected output:
localparam [31:0] TEST7_EXPECTED [0:15] = '{32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536, 32'd-25536};

// Test 8: gradient_values - Gradient values from 1 to 16
// Input matrix:
localparam [15:0] TEST8_INPUT [0:15] = '{16'd1, 16'd2, 16'd3, 16'd4, 16'd5, 16'd6, 16'd7, 16'd8, 16'd9, 16'd10, 16'd11, 16'd12, 16'd13, 16'd14, 16'd15, 16'd16};
// Weight matrix:
localparam [15:0] TEST8_WEIGHT [0:15] = '{16'd16, 16'd15, 16'd14, 16'd13, 16'd12, 16'd11, 16'd10, 16'd9, 16'd8, 16'd7, 16'd6, 16'd5, 16'd4, 16'd3, 16'd2, 16'd1};
// Expected output:
localparam [31:0] TEST8_EXPECTED [0:15] = '{32'd80, 32'd70, 32'd60, 32'd50, 32'd240, 32'd214, 32'd188, 32'd162, 32'd400, 32'd358, 32'd316, 32'd274, 32'd560, 32'd502, 32'd444, 32'd386};

// Test 9: sparse_one_element - Only one element is 255, others are 0
// Input matrix:
localparam [15:0] TEST9_INPUT [0:15] = '{16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0};
// Weight matrix:
localparam [15:0] TEST9_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST9_EXPECTED [0:15] = '{32'd255, 32'd255, 32'd255, 32'd255, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0};

// Test 10: sparse_diagonal - Diagonal elements are 255, others are 0
// Input matrix:
localparam [15:0] TEST10_INPUT [0:15] = '{16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd255};
// Weight matrix:
localparam [15:0] TEST10_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST10_EXPECTED [0:15] = '{32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255, 32'd255};

// Test 11: sparse_row - Only one row has non-zero values
// Input matrix:
localparam [15:0] TEST11_INPUT [0:15] = '{16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd128, 16'd128, 16'd128, 16'd128, 16'd0, 16'd0, 16'd0, 16'd0};
// Weight matrix:
localparam [15:0] TEST11_WEIGHT [0:15] = '{16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2};
// Expected output:
localparam [31:0] TEST11_EXPECTED [0:15] = '{32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd1024, 32'd1024, 32'd1024, 32'd1024, 32'd0, 32'd0, 32'd0, 32'd0};

// Test 12: checkerboard_pattern - Checkerboard pattern
// Input matrix:
localparam [15:0] TEST12_INPUT [0:15] = '{16'd255, 16'd0, 16'd255, 16'd0, 16'd0, 16'd255, 16'd0, 16'd255, 16'd255, 16'd0, 16'd255, 16'd0, 16'd0, 16'd255, 16'd0, 16'd255};
// Weight matrix:
localparam [15:0] TEST12_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST12_EXPECTED [0:15] = '{32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510, 32'd510};

// Test 13: incremental_pattern - Values increment from 1 to 16
// Input matrix:
localparam [15:0] TEST13_INPUT [0:15] = '{16'd1, 16'd2, 16'd3, 16'd4, 16'd5, 16'd6, 16'd7, 16'd8, 16'd9, 16'd10, 16'd11, 16'd12, 16'd13, 16'd14, 16'd15, 16'd16};
// Weight matrix:
localparam [15:0] TEST13_WEIGHT [0:15] = '{16'd1, 16'd2, 16'd3, 16'd4, 16'd5, 16'd6, 16'd7, 16'd8, 16'd9, 16'd10, 16'd11, 16'd12, 16'd13, 16'd14, 16'd15, 16'd16};
// Expected output:
localparam [31:0] TEST13_EXPECTED [0:15] = '{32'd90, 32'd100, 32'd110, 32'd120, 32'd202, 32'd228, 32'd254, 32'd280, 32'd314, 32'd356, 32'd398, 32'd440, 32'd426, 32'd484, 32'd542, 32'd600};

// Test 14: symmetric_matrix - Symmetric input matrix
// Input matrix:
localparam [15:0] TEST14_INPUT [0:15] = '{16'd10, 16'd5, 16'd3, 16'd1, 16'd5, 16'd10, 16'd5, 16'd3, 16'd3, 16'd5, 16'd10, 16'd5, 16'd1, 16'd3, 16'd5, 16'd10};
// Weight matrix:
localparam [15:0] TEST14_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST14_EXPECTED [0:15] = '{32'd19, 32'd19, 32'd19, 32'd19, 32'd23, 32'd23, 32'd23, 32'd23, 32'd23, 32'd23, 32'd23, 32'd23, 32'd19, 32'd19, 32'd19, 32'd19};

// Test 15: alternating_pattern - Alternating rows/columns pattern
// Input matrix:
localparam [15:0] TEST15_INPUT [0:15] = '{16'd255, 16'd255, 16'd255, 16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd255, 16'd255, 16'd255, 16'd255, 16'd0, 16'd0, 16'd0, 16'd0};
// Weight matrix:
localparam [15:0] TEST15_WEIGHT [0:15] = '{16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0};
// Expected output:
localparam [31:0] TEST15_EXPECTED [0:15] = '{32'd-2044, 32'd0, 32'd-2044, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd-2044, 32'd0, 32'd-2044, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0};

// Test 16: random_test_1 - Random test 1
// Input matrix:
localparam [15:0] TEST16_INPUT [0:15] = '{16'd102, 16'd225, 16'd179, 16'd234, 16'd92, 16'd98, 16'd14, 16'd245, 16'd106, 16'd99, 16'd71, 16'd153, 16'd188, 16'd65, 16'd20, 16'd203};
// Weight matrix:
localparam [15:0] TEST16_WEIGHT [0:15] = '{16'd102, 16'd240, 16'd121, 16'd34, 16'd210, 16'd239, 16'd214, 16'd151, 16'd74, 16'd222, 16'd202, 16'd145, 16'd87, 16'd189, 16'd116, 16'd109};
// Expected output:
localparam [31:0] TEST16_EXPECTED [0:15] = '{32'd25722, 32'd31147, 32'd-7278, 32'd23368, 32'd-13221, 32'd29379, 32'd-2184, 32'd-18875, 32'd-15369, 32'd28244, 32'd566, 32'd-20011, 32'd-13569, 32'd-27610, 32'd-1290, 32'd-24302};

// Test 17: random_test_2 - Random test 2
// Input matrix:
localparam [15:0] TEST17_INPUT [0:15] = '{16'd99, 16'd226, 16'd103, 16'd146, 16'd151, 16'd68, 16'd130, 16'd160, 16'd149, 16'd69, 16'd52, 16'd112, 16'd1, 16'd76, 16'd87, 16'd212};
// Weight matrix:
localparam [15:0] TEST17_WEIGHT [0:15] = '{16'd235, 16'd26, 16'd157, 16'd68, 16'd37, 16'd91, 16'd129, 16'd51, 16'd191, 16'd140, 16'd187, 16'd1, 16'd20, 16'd243, 16'd160, 16'd19};
// Expected output:
localparam [31:0] TEST17_EXPECTED [0:15] = '{32'd-11316, 32'd7502, 32'd21782, 32'd21135, 32'd495, 32'd1658, 32'd16853, 32'd16906, 32'd-15796, 32'd-20887, 32'd-5598, 32'd15831, 32'd23904, 32'd5102, 32'd-5386, 32'd8059};

// Test 18: random_test_3 - Random test 3
// Input matrix:
localparam [15:0] TEST18_INPUT [0:15] = '{16'd203, 16'd226, 16'd57, 16'd149, 16'd21, 16'd86, 16'd252, 16'd207, 16'd235, 16'd147, 16'd88, 16'd231, 16'd48, 16'd141, 16'd218, 16'd87};
// Weight matrix:
localparam [15:0] TEST18_WEIGHT [0:15] = '{16'd58, 16'd162, 16'd254, 16'd93, 16'd169, 16'd181, 16'd255, 16'd242, 16'd219, 16'd201, 16'd187, 16'd72, 16'd207, 16'd201, 16'd14, 16'd150};
// Expected output:
localparam [31:0] TEST18_EXPECTED [0:15] = '{32'd27758, 32'd-15874, 32'd-9135, 32'd-31047, 32'd-17283, 32'd-19845, 32'd11750, 32'd6423, 32'd-25510, 32'd-2276, 32'd-14207, 32'd-32657, 32'd26828, 32'd29066, 32'd24595, 32'd1796};

// Test 19: random_test_4 - Random test 4
// Input matrix:
localparam [15:0] TEST19_INPUT [0:15] = '{16'd189, 16'd193, 16'd189, 16'd49, 16'd174, 16'd1, 16'd189, 16'd78, 16'd50, 16'd29, 16'd107, 16'd233, 16'd54, 16'd164, 16'd243, 16'd181};
// Weight matrix:
localparam [15:0] TEST19_WEIGHT [0:15] = '{16'd63, 16'd168, 16'd248, 16'd125, 16'd130, 16'd228, 16'd228, 16'd37, 16'd50, 16'd136, 16'd134, 16'd40, 16'd20, 16'd167, 16'd72, 16'd83};
// Expected output:
localparam [31:0] TEST19_EXPECTED [0:15] = '{32'd-18109, 32'd-21429, 32'd-11342, 32'd-23143, 32'd22102, 32'd2654, 32'd8786, 32'd-29715, 32'd16930, 32'd2939, 32'd-15410, 32'd30942, 32'd-25044, 32'd-21333, 32'd30842, 32'd-27975};

// Test 20: random_test_5 - Random test 5
// Input matrix:
localparam [15:0] TEST20_INPUT [0:15] = '{16'd166, 16'd167, 16'd17, 16'd101, 16'd131, 16'd234, 16'd88, 16'd52, 16'd59, 16'd51, 16'd13, 16'd51, 16'd241, 16'd243, 16'd249, 16'd170};
// Weight matrix:
localparam [15:0] TEST20_WEIGHT [0:15] = '{16'd8, 16'd251, 16'd89, 16'd22, 16'd52, 16'd1, 16'd129, 16'd27, 16'd83, 16'd41, 16'd91, 16'd179, 16'd110, 16'd173, 16'd187, 16'd234};
// Expected output:
localparam [31:0] TEST20_EXPECTED [0:15] = '{32'd22533, 32'd-5533, 32'd-8785, 32'd-30698, 32'd26240, 32'd-19817, 32'd-5959, 32'd-28416, 32'd9813, 32'd24216, 32'd22550, 32'd16936, 32'd-11605, 32'd-30719, 32'd-23827, 32'd30678};

