// Auto-generated test vectors for OS architecture
// Generated by golden_model.py

// Test 1: identity_matrix - All inputs and weights are 1
// Input matrix:
localparam [15:0] TEST1_INPUT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Weight matrix:
localparam [15:0] TEST1_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST1_EXPECTED [0:15] = '{32'd3, 32'd1, 32'd0, 32'd0, 32'd1, 32'd3, 32'd1, 32'd0, 32'd0, 32'd1, 32'd3, 32'd1, 32'd0, 32'd0, 32'd1, 32'd3};

// Test 2: constant_matrix - Input=3, Weight=2
// Input matrix:
localparam [15:0] TEST2_INPUT [0:15] = '{16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3, 16'd3};
// Weight matrix:
localparam [15:0] TEST2_WEIGHT [0:15] = '{16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2};
// Expected output:
localparam [31:0] TEST2_EXPECTED [0:15] = '{32'd18, 32'd6, 32'd0, 32'd0, 32'd6, 32'd18, 32'd6, 32'd0, 32'd0, 32'd6, 32'd18, 32'd6, 32'd0, 32'd0, 32'd6, 32'd18};

// Test 3: zero_value - Input=0, Weight=5
// Input matrix:
localparam [15:0] TEST3_INPUT [0:15] = '{16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0};
// Weight matrix:
localparam [15:0] TEST3_WEIGHT [0:15] = '{16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5, 16'd5};
// Expected output:
localparam [31:0] TEST3_EXPECTED [0:15] = '{32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0};

// Test 4: minimum_value - Input=1, Weight=1
// Input matrix:
localparam [15:0] TEST4_INPUT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Weight matrix:
localparam [15:0] TEST4_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST4_EXPECTED [0:15] = '{32'd3, 32'd1, 32'd0, 32'd0, 32'd1, 32'd3, 32'd1, 32'd0, 32'd0, 32'd1, 32'd3, 32'd1, 32'd0, 32'd0, 32'd1, 32'd3};

// Test 5: mixed_boundary - Mixed boundary values (0, 1, 255)
// Input matrix:
localparam [15:0] TEST5_INPUT [0:15] = '{16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1};
// Weight matrix:
localparam [15:0] TEST5_WEIGHT [0:15] = '{16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0, 16'd255, 16'd1, 16'd0};
// Expected output:
localparam [31:0] TEST5_EXPECTED [0:15] = '{32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd765, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd255, 32'd0, 32'd0, 32'd255, 32'd0};

// Test 6: extreme_max - Input=255, Weight=255
// Input matrix:
localparam [15:0] TEST6_INPUT [0:15] = '{16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255};
// Weight matrix:
localparam [15:0] TEST6_WEIGHT [0:15] = '{16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255, 16'd255};
// Expected output:
localparam [31:0] TEST6_EXPECTED [0:15] = '{32'd195075, 32'd65025, 32'd0, 32'd0, 32'd65025, 32'd195075, 32'd65025, 32'd0, 32'd0, 32'd65025, 32'd195075, 32'd65025, 32'd0, 32'd0, 32'd65025, 32'd195075};

// Test 7: large_accumulation - Input=100, Weight=100
// Input matrix:
localparam [15:0] TEST7_INPUT [0:15] = '{16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100};
// Weight matrix:
localparam [15:0] TEST7_WEIGHT [0:15] = '{16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100, 16'd100};
// Expected output:
localparam [31:0] TEST7_EXPECTED [0:15] = '{32'd30000, 32'd10000, 32'd0, 32'd0, 32'd10000, 32'd30000, 32'd10000, 32'd0, 32'd0, 32'd10000, 32'd30000, 32'd10000, 32'd0, 32'd0, 32'd10000, 32'd30000};

// Test 8: gradient_values - Gradient values from 1 to 16
// Input matrix:
localparam [15:0] TEST8_INPUT [0:15] = '{16'd1, 16'd2, 16'd3, 16'd4, 16'd5, 16'd6, 16'd7, 16'd8, 16'd9, 16'd10, 16'd11, 16'd12, 16'd13, 16'd14, 16'd15, 16'd16};
// Weight matrix:
localparam [15:0] TEST8_WEIGHT [0:15] = '{16'd16, 16'd15, 16'd14, 16'd13, 16'd12, 16'd11, 16'd10, 16'd9, 16'd8, 16'd7, 16'd6, 16'd5, 16'd4, 16'd3, 16'd2, 16'd1};
// Expected output:
localparam [31:0] TEST8_EXPECTED [0:15] = '{32'd48, 32'd30, 32'd0, 32'd0, 32'd60, 32'd198, 32'd70, 32'd0, 32'd0, 32'd70, 32'd198, 32'd60, 32'd0, 32'd0, 32'd30, 32'd48};

// Test 9: sparse_one_element - Only one element is 255, others are 0
// Input matrix:
localparam [15:0] TEST9_INPUT [0:15] = '{16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0};
// Weight matrix:
localparam [15:0] TEST9_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST9_EXPECTED [0:15] = '{32'd765, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0};

// Test 10: sparse_diagonal - Diagonal elements are 255, others are 0
// Input matrix:
localparam [15:0] TEST10_INPUT [0:15] = '{16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd255};
// Weight matrix:
localparam [15:0] TEST10_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST10_EXPECTED [0:15] = '{32'd765, 32'd0, 32'd0, 32'd0, 32'd0, 32'd765, 32'd0, 32'd0, 32'd0, 32'd0, 32'd765, 32'd0, 32'd0, 32'd0, 32'd0, 32'd765};

// Test 11: sparse_row - Only one row has non-zero values
// Input matrix:
localparam [15:0] TEST11_INPUT [0:15] = '{16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd128, 16'd128, 16'd128, 16'd128, 16'd0, 16'd0, 16'd0, 16'd0};
// Weight matrix:
localparam [15:0] TEST11_WEIGHT [0:15] = '{16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2, 16'd2};
// Expected output:
localparam [31:0] TEST11_EXPECTED [0:15] = '{32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd256, 32'd768, 32'd256, 32'd0, 32'd0, 32'd0, 32'd0};

// Test 12: checkerboard_pattern - Checkerboard pattern
// Input matrix:
localparam [15:0] TEST12_INPUT [0:15] = '{16'd255, 16'd0, 16'd255, 16'd0, 16'd0, 16'd255, 16'd0, 16'd255, 16'd255, 16'd0, 16'd255, 16'd0, 16'd0, 16'd255, 16'd0, 16'd255};
// Weight matrix:
localparam [15:0] TEST12_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST12_EXPECTED [0:15] = '{32'd765, 32'd0, 32'd0, 32'd0, 32'd0, 32'd765, 32'd0, 32'd0, 32'd0, 32'd0, 32'd765, 32'd0, 32'd0, 32'd0, 32'd0, 32'd765};

// Test 13: incremental_pattern - Values increment from 1 to 16
// Input matrix:
localparam [15:0] TEST13_INPUT [0:15] = '{16'd1, 16'd2, 16'd3, 16'd4, 16'd5, 16'd6, 16'd7, 16'd8, 16'd9, 16'd10, 16'd11, 16'd12, 16'd13, 16'd14, 16'd15, 16'd16};
// Weight matrix:
localparam [15:0] TEST13_WEIGHT [0:15] = '{16'd1, 16'd2, 16'd3, 16'd4, 16'd5, 16'd6, 16'd7, 16'd8, 16'd9, 16'd10, 16'd11, 16'd12, 16'd13, 16'd14, 16'd15, 16'd16};
// Expected output:
localparam [31:0] TEST13_EXPECTED [0:15] = '{32'd3, 32'd4, 32'd0, 32'd0, 32'd25, 32'd108, 32'd49, 32'd0, 32'd0, 32'd100, 32'd363, 32'd144, 32'd0, 32'd0, 32'd225, 32'd768};

// Test 14: symmetric_matrix - Symmetric input matrix
// Input matrix:
localparam [15:0] TEST14_INPUT [0:15] = '{16'd10, 16'd5, 16'd3, 16'd1, 16'd5, 16'd10, 16'd5, 16'd3, 16'd3, 16'd5, 16'd10, 16'd5, 16'd1, 16'd3, 16'd5, 16'd10};
// Weight matrix:
localparam [15:0] TEST14_WEIGHT [0:15] = '{16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1, 16'd1};
// Expected output:
localparam [31:0] TEST14_EXPECTED [0:15] = '{32'd30, 32'd5, 32'd0, 32'd0, 32'd5, 32'd30, 32'd5, 32'd0, 32'd0, 32'd5, 32'd30, 32'd5, 32'd0, 32'd0, 32'd5, 32'd30};

// Test 15: alternating_pattern - Alternating rows/columns pattern
// Input matrix:
localparam [15:0] TEST15_INPUT [0:15] = '{16'd255, 16'd255, 16'd255, 16'd255, 16'd0, 16'd0, 16'd0, 16'd0, 16'd255, 16'd255, 16'd255, 16'd255, 16'd0, 16'd0, 16'd0, 16'd0};
// Weight matrix:
localparam [15:0] TEST15_WEIGHT [0:15] = '{16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0, 16'd255, 16'd0};
// Expected output:
localparam [31:0] TEST15_EXPECTED [0:15] = '{32'd195075, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0, 32'd195075, 32'd0, 32'd0, 32'd0, 32'd0, 32'd0};

// Test 16: random_test_1 - Random test 1
// Input matrix:
localparam [15:0] TEST16_INPUT [0:15] = '{16'd102, 16'd225, 16'd179, 16'd234, 16'd92, 16'd98, 16'd14, 16'd245, 16'd106, 16'd99, 16'd71, 16'd153, 16'd188, 16'd65, 16'd20, 16'd203};
// Weight matrix:
localparam [15:0] TEST16_WEIGHT [0:15] = '{16'd102, 16'd240, 16'd121, 16'd34, 16'd210, 16'd239, 16'd214, 16'd151, 16'd74, 16'd222, 16'd202, 16'd145, 16'd87, 16'd189, 16'd116, 16'd109};
// Expected output:
localparam [31:0] TEST16_EXPECTED [0:15] = '{32'd31212, 32'd54000, 32'd0, 32'd0, 32'd19320, 32'd70266, 32'd2996, 32'd0, 32'd0, 32'd21978, 32'd43026, 32'd22185, 32'd0, 32'd0, 32'd2320, 32'd66381};

// Test 17: random_test_2 - Random test 2
// Input matrix:
localparam [15:0] TEST17_INPUT [0:15] = '{16'd99, 16'd226, 16'd103, 16'd146, 16'd151, 16'd68, 16'd130, 16'd160, 16'd149, 16'd69, 16'd52, 16'd112, 16'd1, 16'd76, 16'd87, 16'd212};
// Weight matrix:
localparam [15:0] TEST17_WEIGHT [0:15] = '{16'd235, 16'd26, 16'd157, 16'd68, 16'd37, 16'd91, 16'd129, 16'd51, 16'd191, 16'd140, 16'd187, 16'd1, 16'd20, 16'd243, 16'd160, 16'd19};
// Expected output:
localparam [31:0] TEST17_EXPECTED [0:15] = '{32'd69795, 32'd5876, 32'd0, 32'd0, 32'd5587, 32'd18564, 32'd16770, 32'd0, 32'd0, 32'd9660, 32'd29172, 32'd112, 32'd0, 32'd0, 32'd13920, 32'd12084};

// Test 18: random_test_3 - Random test 3
// Input matrix:
localparam [15:0] TEST18_INPUT [0:15] = '{16'd203, 16'd226, 16'd57, 16'd149, 16'd21, 16'd86, 16'd252, 16'd207, 16'd235, 16'd147, 16'd88, 16'd231, 16'd48, 16'd141, 16'd218, 16'd87};
// Weight matrix:
localparam [15:0] TEST18_WEIGHT [0:15] = '{16'd58, 16'd162, 16'd254, 16'd93, 16'd169, 16'd181, 16'd255, 16'd242, 16'd219, 16'd201, 16'd187, 16'd72, 16'd207, 16'd201, 16'd14, 16'd150};
// Expected output:
localparam [31:0] TEST18_EXPECTED [0:15] = '{32'd35322, 32'd36612, 32'd0, 32'd0, 32'd3549, 32'd46698, 32'd64260, 32'd0, 32'd0, 32'd29547, 32'd49368, 32'd16632, 32'd0, 32'd0, 32'd3052, 32'd39150};

// Test 19: random_test_4 - Random test 4
// Input matrix:
localparam [15:0] TEST19_INPUT [0:15] = '{16'd189, 16'd193, 16'd189, 16'd49, 16'd174, 16'd1, 16'd189, 16'd78, 16'd50, 16'd29, 16'd107, 16'd233, 16'd54, 16'd164, 16'd243, 16'd181};
// Weight matrix:
localparam [15:0] TEST19_WEIGHT [0:15] = '{16'd63, 16'd168, 16'd248, 16'd125, 16'd130, 16'd228, 16'd228, 16'd37, 16'd50, 16'd136, 16'd134, 16'd40, 16'd20, 16'd167, 16'd72, 16'd83};
// Expected output:
localparam [31:0] TEST19_EXPECTED [0:15] = '{32'd35721, 32'd32424, 32'd0, 32'd0, 32'd22620, 32'd684, 32'd43092, 32'd0, 32'd0, 32'd3944, 32'd43014, 32'd9320, 32'd0, 32'd0, 32'd17496, 32'd45069};

// Test 20: random_test_5 - Random test 5
// Input matrix:
localparam [15:0] TEST20_INPUT [0:15] = '{16'd166, 16'd167, 16'd17, 16'd101, 16'd131, 16'd234, 16'd88, 16'd52, 16'd59, 16'd51, 16'd13, 16'd51, 16'd241, 16'd243, 16'd249, 16'd170};
// Weight matrix:
localparam [15:0] TEST20_WEIGHT [0:15] = '{16'd8, 16'd251, 16'd89, 16'd22, 16'd52, 16'd1, 16'd129, 16'd27, 16'd83, 16'd41, 16'd91, 16'd179, 16'd110, 16'd173, 16'd187, 16'd234};
// Expected output:
localparam [31:0] TEST20_EXPECTED [0:15] = '{32'd3984, 32'd41917, 32'd0, 32'd0, 32'd6812, 32'd702, 32'd11352, 32'd0, 32'd0, 32'd2091, 32'd3549, 32'd9129, 32'd0, 32'd0, 32'd46563, 32'd119340};

