ARCH_NAME := DIP
ARCH_KEY := dip
TB_MAIN := $(abspath $(CURDIR)/../tb/standard_dip_smoke_tb.sv)
TB_TOP := standard_dip_smoke_tb
TB_WAVE := $(abspath $(CURDIR)/../tb/systolic_array_dip_latency_tb.v)
TB_WAVE_TOP := systolic_array_dip_latency_tb
include $(abspath $(CURDIR)/../../scripts/arch_common.mk)
