// Auto-generated testbench for test1_identity
// Generated by golden_model.py

`timescale 1ns/1ps

module auto_test_test1_identity;

    parameter DATA_WIDTH = 16;
    parameter WEIGHT_WIDTH = 16;
    parameter ACC_WIDTH = 32;
    parameter CLK_PERIOD = 10;

    reg clk;
    reg rst_n;
    reg [WEIGHT_WIDTH-1:0] weight_in;
    reg weight_valid;
    reg weight_load;
    wire weight_ready;

    reg [DATA_WIDTH-1:0] input_data;
    reg input_valid;
    wire input_ready;

    wire [ACC_WIDTH*4-1:0] output_data;
    wire [3:0] output_valid;
    reg [3:0] output_ready;

    reg flush;
    wire busy;
    reg clk_enable;

    // DUT instantiation
    systolic_array_4x4 #(
        .DATA_WIDTH(DATA_WIDTH),
        .WEIGHT_WIDTH(WEIGHT_WIDTH),
        .ACC_WIDTH(ACC_WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .weight_in(weight_in),
        .weight_valid(weight_valid),
        .weight_load(weight_load),
        .weight_ready(weight_ready),
        .input_data(input_data),
        .input_valid(input_valid),
        .input_ready(input_ready),
        .output_data(output_data),
        .output_valid(output_valid),
        .output_ready(output_ready),
        .flush(flush),
        .clk_enable(clk_enable),
        .busy(busy)
    );

    // Clock generation
    initial begin
        clk = 0;
        forever #(CLK_PERIOD/2) clk = ~clk;
    end

    // Golden reference values
    reg signed [ACC_WIDTH-1:0] golden_output [0:3][0:3];

    initial begin
        // Initialize golden outputs from Python model
        golden_output[0][0] = 32'd4;
        golden_output[0][1] = 32'd4;
        golden_output[0][2] = 32'd4;
        golden_output[0][3] = 32'd4;
        golden_output[1][0] = 32'd4;
        golden_output[1][1] = 32'd4;
        golden_output[1][2] = 32'd4;
        golden_output[1][3] = 32'd4;
        golden_output[2][0] = 32'd4;
        golden_output[2][1] = 32'd4;
        golden_output[2][2] = 32'd4;
        golden_output[2][3] = 32'd4;
        golden_output[3][0] = 32'd4;
        golden_output[3][1] = 32'd4;
        golden_output[3][2] = 32'd4;
        golden_output[3][3] = 32'd4;

        // Initialize signals
        rst_n = 0;
        weight_in = 0;
        weight_valid = 0;
        weight_load = 0;
        input_data = 0;
        input_valid = 0;
        output_ready = 4'b0000;
        flush = 0;
        clk_enable = 1;

        repeat(5) @(posedge clk);
        rst_n = 1;
        repeat(2) @(posedge clk);

        $display("\n========================================");
        $display("Automated Test: {test_name}");
        $display("========================================\n");

        // Load weights
        $display("Loading weights...");
        weight_load = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        @(posedge clk); weight_in = 16'd1; weight_valid = 1;
        weight_valid = 0;
        weight_load = 0;

        repeat(5) @(posedge clk);

        // Send inputs
        $display("Sending inputs...");
        output_ready = 4'b1111;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        @(posedge clk); input_data = 16'd1; input_valid = 1;
        input_valid = 0;

        // Wait for outputs
        repeat(50) @(posedge clk);

        // Verify outputs
        $display("\n========================================");
        $display("Verification Results");
        $display("========================================");

        fork
            begin
                repeat(100) @(posedge clk);
            end
            begin
                wait(output_valid[0]);
                repeat(5) @(posedge clk);  // Wait for all outputs
            end
        join_any

        // Check each output
        integer i, j, errors;
        errors = 0;

        for (i = 0; i < 4; i = i + 1) begin
            for (j = 0; j < 4; j = j + 1) begin
                automatic logic [31:0] actual = output_data[i*32 +: 32];
                automatic logic [31:0] expected = golden_output[i][j];

                if (actual !== expected) begin
                    $display("❌ ERROR: C[%0d][%0d] = %0d (expected %0d)",
                             i, j, $signed(actual), $signed(expected));
                    errors = errors + 1;
                end else begin
                    $display("✅ OK: C[%0d][%0d] = %0d", i, j, $signed(actual));
                end
            end
        end

        $display("\n========================================");
        if (errors == 0) begin
            $display("✅ TEST PASSED: All outputs match golden model");
        end else begin
            $display("❌ TEST FAILED: %0d mismatches detected", errors);
        end
        $display("========================================\n");

        $finish;
    end

endmodule
